### ISSUE TITLE
Add Firebase code to repo

### ISSUE THREAD

**Issue by alfalcon90** [Tinytown/tinytown-react-app#60]
We need to bring the Firebase code into the repo. I think creating a monorepo, in this case, is the right approach given the small amount of complexity and tight coupling between the app and the backend. 

**Tasks**
- [x] Integrate Firebase with Doppler
- [x] Extract setup.js to root folder
- [ ] Keep README and CONTRIBUTING at the root level
- [x] Create new folder for app codebase: react-app
- [x] Run cloud functions through local emulator if in dev environment
